### ISSUE TITLE
False Positive: ocsp.apple.com

### ISSUE THREAD

**Issue by p1r473** [ReddestDream/reddestdream.github.io#3]
This is the certificate validation server for apple
https://support.apple.com/en-us/HT210060

**Comment by ReddestDream** [comment]
I don't maintain this really anymore. That address was blocked in order to keep an older jailbreak from breaking. Thanks!

Also see my response here: https://github.com/ReddestDream/reddestdream.github.io/issues/2#issuecomment-394174049
